### ISSUE TITLE
Deployer can't deploy in protected areas

### ISSUE THREAD

**Issue by AmyMoriyama** [loosewheel/lwcomponents#2]
So, I was trying to create sort of automatic farm using the deployer and it works fine outside of protected areas, but as soon as you protect the area (using areas mod), it stops placing.

**Comment by loosewheel** [comment]
Unfortunately the minetest api doesn’t well support automation (when something other than a player is performing an action). Most actions can be easily implemented but placing nodes isn’t so straight forward.

This mod doesn’t try to do everything the other mods do for them. It tries to get the mod for the item being placed to place it by calling it’s functions. These functions often crash because they expect a player to be doing it, and when that happens this mod uses a simple placement method instead (which works most of the time).

The reason the items aren’t placing in protected areas is because the mod placing them doesn’t have a player to check, so it will only place them in areas with no protection at all.

To work around this I added a mod setting "Use player when placing", which is disabled by default. If it is enabled then for a locked deployer, which has an owner, the player for the owner will be given to the other mod’s function. This has some short comings though:

1) Mods sometimes use information from the player (as well as other information) to place the item. Things such as the player’s name (which protection needs) and the players direction are often used. I tested this with several items from the farming mod and they seem to work OK. But other mods, now getting a player, may uses this information from a player that may be far away and looking in any direction. That is to say, weird things might happen.

2) For multi-player games (where protection is probably most used) when the owner is not logged in there is no player, so it will still do what is does now.

The protection in deployers and breakers was not implemented as well as it could, which I’ve fixed up. For either of these to work in protected areas they must be the locked version and the owner must be able to dig/place in the area.
